Allow to pass application name to the postgres connection.
fukamachi/cl-dbi pull request #87
Opened 2024-06-28 06:49 UTC by svetlyak40wt

2024-06-29 12:26 UTC, fukamachi requested changes
Thank you for the patch!
Only one thing I'd like to make a change.

2024-06-29 12:26 UTC, fukamachi commented on src/dbd/postgres.lisp
> +(defmethod make-connection ((driver dbd-postgres) &key database-name username password (host "localhost") (port 5432) (use-ssl :no) (microsecond-precision nil) (service "postgres") (application-name
Can the default value of `application-name` be an empty string which is the default of cl-postgres?

2024-06-29 20:33 UTC, svetlyak40wt commented on src/dbd/postgres.lisp
> +(defmethod make-connection ((driver dbd-postgres) &key database-name username password (host "localhost") (port 5432) (use-ssl :no) (microsecond-precision nil) (service "postgres") (application-name
Actually, `postmodern-default` is the default application name for connection in cl-postgres:

https://github.com/marijnh/Postmodern/blob/3147c7dffcbc9f6dbf2cc34e4705aef114e14b9e/cl-postgres/public.lisp#L29

I've noticed that all my connections from cl-dbi to postgres have this application name and decided it will be good to keep it for backward compatibility.

2024-07-01 05:59 UTC, fukamachi commented on src/dbd/postgres.lisp
> +(defmethod make-connection ((driver dbd-postgres) &key database-name username password (host "localhost") (port 5432) (use-ssl :no) (microsecond-precision nil) (service "postgres") (application-name
Okay, then let's keep it as you suggested.
Thanks!

2024-07-01 05:59 UTC, merged